{% set name = "napari-stl-exporter" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-stl-exporter-{{ version }}.tar.gz
  sha256: 18c45e82e0eec94ba03a2570630390c59e5e726bd3aea7fb79235cabc48c0dc7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - numpy-stl
    - python >=3.7
    - scikit-image
    - vedo

test:
  commands:
    - pip list
    - pip check || true
    - xvfb-run -a python -c "import napari_stl_exporter; print('import OK')"
  requires:
    - pip

about:
  home: https://github.com/jo-mueller/napari-stl-exporter
  summary: Exports label images to 3D-printable stl files.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - jo-mueller
