{% set name = "napari-stl-exporter" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jo-mueller/napari-stl-exporter/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c406e5d53e05357efd5b20d5c6f4e593f01334f661c2bb9eaf2cb80fc0c3a300
  patches:
    - setup_cfg.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - scikit-image
    - vedo
    - npe2

test:
  commands:
    - pip list
    - pip check || true
    - xvfb-run -a python -c "import napari_stl_exporter; print('import OK')"
  requires:
    - pip

about:
  home: https://github.com/jo-mueller/napari-stl-exporter
  summary: Exports label images to 3D-printable stl files.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jo-mueller
