{% set name = "napari-stl-exporter" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-stl-exporter-{{ version }}.tar.gz
  sha256: a16d9f6cd277e480d7cf25ac9c4e461d5d31a76964628fdb8f7f827d1ef8e1fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari-plugin-engine >=0.1.4
    - numpy
    - numpy-stl
    - python >=3.7
    - scikit-image

test:
  imports:
    - napari_stl_exporter
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jo-mueller/napari-stl-exporter
  summary: Exports label images to 3D-printable stl files.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - jo-mueller
